version: "3.9"
services:
  database:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: rails-starter_dev_password
  web:
    build: .
    platform: linux/amd64
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails-starter:cached
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      RAILS_ENV: development
      DATABASE_NAME: rails-starter_development
      DATABASE_USER: postgres
      DATABASE_PASSWORD: rails-starter_dev_password
      DATABASE_HOST: database

volumes:
  db_data: